version: 2
updates:
  # Backend .NET
  - package-ecosystem: "nuget"
    directory: "/src/ProvaVida.Api"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5

  # App Mobile .NET MAUI
  - package-ecosystem: "nuget"
    directory: "/mobile/ProvaVida.Maui"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
