<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\ProvaVida.Shared.csproj" />
    <ProjectReference Include="..\ProvaVida.Mobile.Domain\ProvaVida.Mobile.Domain.csproj" />
    <ProjectReference Include="..\ProvaVida.Mobile.Application\ProvaVida.Mobile.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dbup-sqlite" Version="6.0.4" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Migrations\V001__criar_tabela_usuarios.sql" />
    <EmbeddedResource Include="Migrations\V002__criar_tabela_checkins.sql" />
  </ItemGroup>

</Project>
